ALTER TABLE bills DROP COLUMN sent_at;
ALTER TABLE bills DROP COLUMN created_at;
ALTER TABLE bills ADD COLUMN sent_at TIMESTAMP WITH TIME ZONE DEFAULT null;
ALTER TABLE bills ADD COLUMN created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL;
